# We could use `@actions-rs/cargo` Action ability to automatically install `cross` tool
# in order to compile our application for some unusual targets.

# on: [push, pull_request]

name: Cross Compile Rust Application

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions: 
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # - name: Checkout Repository
      #   uses: actions/checkout@v3
        # with: 
        #   path: master

      - uses: actions/checkout@v2
      - name: Set Up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      
      # - name: Install Dependencies
      #   run: |
      #     # Add any dependency installations you need here
      #     # Example (for Ubuntu): sudo apt update && sudo apt-get install -y build-essential
      #     # Example (for Windows): choco install -y visualstudio2019buildtools

      - name: Cross Compile for Linux
        if: startsWith(matrix.os, 'ubuntu')
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Cross Compile for macOS
        if: startsWith(matrix.os, 'macos')
        run: cargo build --release --target x86_64-apple-darwin

      - name: Cross Compile for Windows
        if: startsWith(matrix.os, 'windows')
        run: cargo build --release --target x86_64-pc-windows-gnu
        # You may also want to generate a standalone executable:
        # run: cargo build --release --target x86_64-pc-windows-gnu --features standalone

      - name: Archive Builds
        run: |
          mkdir artifacts
          if [[ "$RUNNER_OS" == "Linux" ]]; then 
            cp target/x86_64-unknown-linux-gnu/release/rust-string-replacer artifacts/rust-string-replacer-linux
            echo "ubuntu artifact copied successfully."
          elif [[ "$RUNNER_OS" == "macOS" ]]; then 
            cp target/x86_64-apple-darwin/release/rust-string-replacer artifacts/rust-string-replacer-osx
            echo "osx artifact copied successfully."
          elif [[ "$RUNNER_OS" == "Windows" ]]; then 
            cp target/x86_64-pc-windows-gnu/release/rust-string-replacer.exe artifacts/rust-string-replacer.exe
            echo "windows artifact copied successfully."
          else 
            echo "ERROR: $RUNNER_OS not supported"
            exit 1 
          fi
        shell: bash

      - name: Upload Builds
        uses: actions/upload-artifact@v3
        with:
          name: cross-compiled-builds
          path: artifacts/*
          if-no-files-found: error

  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            artifacts/rust-string-replacer-linux
            artifacts/rust-string-replacer-osx
            artifacts/rust-string-replacer.exe
          fail_on_unmatched_files: true
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
